name: Push Docker Image

on:
  push:
    branches:
      - develop  # Trigger the workflow when code is pushed to the 'develop' branch.

jobs:
  build:
    runs-on: self-hosted  # Use a self-hosted runner. If using GitHub-hosted runners, change to 'ubuntu-latest'.

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code.
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version you want to use.

    - name: Install dependencies
      run: npm install  # Install the dependencies from package.json.

    - name: Create build
      run: npm run build  # Run the build command (e.g., for React or Node.js).

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Login to Docker Hub.
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username stored in GitHub secrets.
        password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password stored in GitHub secrets.

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3  # Extract Docker image metadata like tags.
      with:
        images: sachinvel59/testjodejsapp  # Replace with your Docker image name.

    - name: Build and push Docker image
      # uses: docker/build-push-action@v3  # Build and push the Docker image.
      # with:
      #   context: .  # Build from the current directory.
      #   push: true  # Push the image to Docker Hub after building.
      #   tags: ${{ steps.meta.outputs.tags }}  # Use tags generated by the metadata action.
      #   labels: ${{ steps.meta.outputs.labels }}  # Use labels generated by the metadata action.
