name: Push Docker Image

on:
  push:
    branches:
      - develop  # Trigger workflow on push to the develop branch

jobs:
  build:
    runs-on: self-hosted  # Use a self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository
    
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Set up Node.js
      with:
        node-version: '20'  # Specify the version of Node.js you're using
    
    - name: Install dependencies
      run: npm install  # Install dependencies from package.json

    - name: Create build
      run: npm run build  # Build your project (e.g., React or Node.js)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Log in to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in secrets

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3  # Extract metadata like tags and labels for the Docker image
      with:
        images: sachinvel59/testjodejsapp  # Replace with your image name (ensure the name is correct)

    - name: Build and push Docker image
      # uses: docker/build-push-action@v3  # Build and push the Docker image to Docker Hub
      # with:
      #   context: .  # Specify the build context (current directory)
      #   push: true  # Push the built image to Docker Hub
      #   tags: ${{ steps.meta.outputs.tags }}  # Use the generated tags from the metadata action
      #   labels: ${{ steps.meta.outputs.labels }}  # Use the generated labels from the metadata action
