name: Publish Docker image

on:
  push:
    branches:
      - 'develop'  # Trigger the workflow on pushes to the 'develop' branch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out the repo
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Create build
      - name: Create build
        run: npm run build

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: sachinvel59/testjodejsapp  # Update the image name accordingly

      # Build and push Docker image
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
