name: project_Frontend_1

on:
  push:
    branches:
      - develop  

jobs:
  build-node:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install  

      - name: Build the project
        run: npm run build  

  build-docker:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner for the second job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Pull the latest Docker image
        run: docker pull sachin816/front:latest 

      - name: Build Docker image
        run: docker build -t sachin816/front .

      # Uncomment the following step if you want to push the image to Docker Hub after building it
      # - name: Push Docker image to Docker Hub
      #   run: docker push sachin816/front  # Push the built image to Docker Hub

  # deploy-docker:
  #   runs-on: self-hosted  # Uncomment and modify this section if you want to deploy the Docker container after building

  #   steps:
  #     - name: Pull Docker image
  #       run: sudo docker pull sachin816/front:${{ github.sha }}  # Pull the image tagged with the GitHub SHA

  #     - name: Delete old Docker container
  #       run: sudo docker rm -f container || true  # Remove old container if exists

  #     - name: Run Docker container
  #       run: sudo docker run -d -p 8010:80 --name container sachin816/front:${{ github.sha }}  # Run the container on port 8010
