name: Push the image 

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install
      
      - name: Create build
        run: npm run build

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker Image
        run: docker build -t image1 .

      - name: Publish image to Docker Hub
        run: docker push sachin816/image1

  # deploy: 
  #   needs: build
  #   runs-on: ubuntu-latest 
  #   steps:
  #     - name: Checkout Source
  #       uses: actions/checkout@v3
  #     - name: Login to Docker Hub
  #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Pull image from Docker Hub
  #       run: docker pull sachin816/image1  
  #     - name: Delete Old Container
  #       run: docker rm -f reactContainer || true
  #     - name: Run Docker Container
  #       run: docker run -itd --name cont1 -p "8010:5000" image1
