name: Project_Frontend

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
