name: Push the Docker Image

on:
  push:
    branches:
      - develop  # This will trigger the workflow on pushes to the 'develop' branch.

jobs:
  build:
    runs-on: self-hosted  # Specify a self-hosted runner for this job.
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code.

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version you're using.

    - name: Install dependencies
      run: npm install  # Install the dependencies defined in package.json.

    - name: Create build
      run: npm run build  # Build the project (e.g., for React or a Node.js project).

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Use version 2 for Docker login action.
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in secrets.
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in secrets.

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3  # Use version 3 of metadata-action.
      with:
        images: sachinvel59/testjodejsapp  # Replace with your Docker image name.

    - name: Build and push Docker image
      # uses: docker/build-push-action@v3  # Use version 3 of build-push-action.
      # with:
      #   context: .  # Build from the current directory.
      #   push: true  # Push the image to Docker Hub.
      #   tags: ${{ steps.meta.outputs.tags }}  # Use the generated tags from metadata action.
      #   labels: ${{ steps.meta.outputs.labels }}  # Use the generated labels from metadata action.
